require("config")

-- vim commands
vim.cmd("set number")
vim.cmd("set relativenumber")
vim.cmd("hi LineNr guibg=none")
vim.cmd("set tabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set expandtab")
vim.cmd("set signcolumn=no")
vim.cmd("set path=.,,**")
vim.cmd("set splitbelow")
vim.cmd("set wildmenu")
vim.cmd("set wildmode=longest,list")
vim.cmd("set guicursor=n-v-c-i:block")
vim.cmd("set showmatch")
vim.cmd("set completeopt=menu,preview,noinsert")
